### ISSUE TITLE
Error: unknown response type

### ISSUE THREAD

**Issue by dbeqiraj** [actions-on-google/dialogflow-conversation-components-nodejs#13]
I'm new to dialogflow and I wanted to use TableCard in my application to represent a response to the user. I tried it as following but it's not working:

```
'use strict';

const functions = require('firebase-functions');
const {WebhookClient} = require('dialogflow-fulfillment');
const {Carousel, Table} = require('actions-on-google');

process.env.DEBUG = 'dialogflow:debug';

exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
	const agent = new WebhookClient({ request, response });
	
	function myIntentName(){
	
		agent.add(new Table({
			dividers: true,
			columns: ['header 1', 'header 2', 'header 3'],
			rows: [
			  ['row 1 item 1', 'row 1 item 2', 'row 1 item 3'],
			  ['row 2 item 1', 'row 2 item 2', 'row 2 item 3'],
			],
		  }));
	}
	
	
	let intentMap = new Map();
	
	intentMap.set('myIntentName', myIntentName);
	
	agent.handleRequest(intentMap);
	
});
```
And this is the error:
```
Error: unknown response type
    at WebhookClient.add (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:225:13)
    at cosaPuoiFare (/user_code/index.js:790:9)
    at WebhookClient.handleRequest (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:251:44)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:829:8)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:26:47)
    at /var/tmp/worker/worker.js:689:7
    at /var/tmp/worker/worker.js:673:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Do you have any idea why it's not working?

**Comment by LeonNicholls** [comment]
The table card is only available for Actions on Google fulfillment and not pure Dialogflow fulfillment as you have. Take a look at this sample for using table cards with Actions on Google: https://github.com/actions-on-google/dialogflow-conversation-components-nodejs/blob/master/functions/index.js

**Comment by dbeqiraj** [comment]
@entertailion Thank you for this information. Are there other cards like BasicCard, Carousel, List, Media, etc. that I **cannot** use in pure Dialogflow fulfillment?

**Comment by LeonNicholls** [comment]
Dialogflow supports generic responses like Text, Cards, Images and Suggestion Chips (Quick Replies).
The Actions on Google rich responses are only supported for Actions on Google fulfillment.
