### ISSUE TITLE
Error Unknown response type Json

### ISSUE THREAD

**Issue by bhaveshbusa** [actions-on-google/dialogflow-conversation-components-nodejs#17]
I am getting an error parsing a Json response. With my limited understanding of Json is it because the response start with array.

I am using request library
https://github.com/request/request

And I am getting the data from the following service.
https://api.tfl.gov.uk/StopPoint/490002072A/Arrivals

```
Error: Unknown response type: "{"statusCode":200,"body":[{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"-580534719","operationType":1,"vehicleId":"BF65WJK","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"119","lineName":"119","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"Purley Way, Colonnades","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":156,"currentLocation":"","towards":"South Croydon or West Croydon","expectedArrival":"2019-02-27T09:40:14Z","timeToLive":"2019-02-27T09:40:44Z","modeName":"bus","timing":{"$type":"Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities","countdownServerAdjustment":"-00:00:02.6243184","source":"2019-02-27T02:35:21.836Z","insert":"2019-02-27T09:36:59.861Z","read":"2019-02-27T09:36:57.155Z","sent":"2019-02-27T09:37:38Z","received":"0001-01-01T00:00:00Z"}},{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"-739400795","operationType":1,"vehicleId":"BP15OLT","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"119","lineName":"119","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"Purley Way, Colonnades","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":891,"currentLocation":"","towards":"South Croydon or West Croydon","expectedArrival":"2019-02-27T09:52:29Z","timeToLive":"2019-02-27T09:52:59Z","modeName":"bus","timing":{"$type":"Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities","countdownServerAdjustment":"-00:00:02.6751628","source":"2019-02-27T02:35:21.836Z","insert":"2019-02-27T09:37:09.88Z","read":"2019-02-27T09:37:07.17Z","sent":"2019-02-27T09:37:38Z","received":"0001-01-01T00:00:00Z"}},{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"1989751219","operationType":1,"vehicleId":"BP15OMB","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"119","lineName":"119","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"Purley Way, Colonnades","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":1745,"currentLocation":"","towards":"South Croydon or West Croydon","expectedArrival":"2019-02-27T10:06:43Z","timeToLive":"2019-02-27T10:07:13Z","modeName":"bus","timing":{"$type":"Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities","countdownServerAdjustment":"-00:00:02.7104852","source":"2019-02-27T02:35:21.836Z","insert":"2019-02-27T09:37:14.52Z","read":"2019-02-27T09:37:11.825Z","sent":"2019-02-27T09:37:38Z","received":"0001-01-01T00:00:00Z"}},{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"1698915770","operationType":1,"vehicleId":"LJ08CTE","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"194","lineName":"194","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"West Croydon","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":1532,"currentLocation":"","towards":"South Croydon or West Croydon","expectedArrival":"2019-02-27T10:03:10Z","timeToLive":"2019-02-27T10:03:40Z","modeName":"bus","timing":{"$type":"Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities","countdownServerAdjustment":"-00:00:02.7146433","source":"2019-02-27T02:35:21.836Z","insert":"2019-02-27T09:36:49.846Z","read":"2019-02-27T09:36:47.139Z","sent":"2019-02-27T09:37:38Z","received":"0001-01-01T00:00:00Z"}},{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"-15610565","operationType":1,"vehicleId":"LJ13CHY","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"194","lineName":"194","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"West Croydon","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":634,"currentLocation":"","towards":"South Croydon or West Croydon","expectedArrival":"2019-02-27T09:48:12Z","timeToLive":"2019-02-27T09:48:42Z","modeName":"bus","timing":{"$type":"Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities","countdownServerAdjustment":"-00:00:02.6688867","source":"2019-02-27T02:35:21.836Z","insert":"2019-02-27T09:36:49.846Z","read":"2019-02-27T09:36:47.139Z","sent":"2019-02-27T09:37:38Z","received":"0001-01-01T00:00:00Z"}},{"$type":"Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities","id":"-1803100894","operationType":1,"vehicleId":"LJ10HVE","naptanId":"490002072A","stationName":"Sandilands Tram Stop","lineId":"198","lineName":"198","platformName":"U","direction":"outbound","bearing":"273","destinationNaptanId":"","destinationName":"Thornton Heath, High Street","timestamp":"2019-02-27T09:37:38.4799254Z","timeToStation":1160,"currentLocation":"","towards":"South Croydon
```

**Comment by Fleker** [comment]
It appears to be valid based on jsonlint.com

Is this error happening when trying to use Dialogflow?

**Comment by bhaveshbusa** [comment]
It turned to be **error in my script**. Looking at the stack trace in Firebase console I made the assumption DialogFlow was not able to parse the JSON.

` at WebhookClient.addResponse_ (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:277:13)
    at responses.forEach (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:243:51)`
